### ISSUE TITLE
Test failures (old redis-server?)

### ISSUE THREAD

**Issue by eserte** [binary-com/perl-Cache-RedisDB#4]
On some systems make test fails with a line
```
ERR wrong number of arguments for 'set' command# Tests were run but no plan was declared and done_testing() was not seen.
```
A sample fail report can be seen here: http://www.cpantesters.org/cpan/report/ae56db2e-b4dd-11e4-8dff-08b1e0bfc7aa

Maybe this is related to an older version of redis-server? I observe the failures on systems with the following redis-server version:
* Redis server version 2.4.14 (debian/wheezy)

And no failures with these versions:
* Redis server v=2.8.17 (debian/jessie)
* Redis server v=2.8.19 (freebsd 9 & 10)

**Comment by einhverfr** [comment]
Hi.  Thanks for the information.  This sounds like something we should start by documenting and see if we can autodetect somehow.

At any rate, will see what I can do about this within the week.  I am also wondering if there are concurrency issues here.

It seems you are correct.  It seems identical to these:
https://github.com/redis/redis-rb/issues/372

**Comment by einhverfr** [comment]
I think the latest pull request should do it.  Feel free to test.  Otherwise waiting for cpantesters confirmation before I release 0.09

**Comment by eserte** [comment]
My test results can be found here: http://matrix.cpantesters.org/?dist=Cache-RedisDB%200.080_4
Looks good so far.
